name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd ciphers_project
        python manage.py test
    - name: Build and push the image
      run: |
          docker login --username Nivedithabp --password ${{secrets.TEST}} ghcr.io
          docker build -t ghcr.io/nivedithabp/calculator:latest --file Dockerfile .
          docker push ghcr.io/nivedithabp/calculator:latest    
